# Generated by Django 5.2.8 on 2025-12-04 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.catagory'),
            preserve_default=False,
        ),
    ]
